# Generated by Django 2.0 on 2017-12-31 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='streak',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
