# Generated by Django 2.0 on 2017-12-29 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('las_site', '0002_auto_20171228_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='image',
            field=models.URLField(),
        ),
    ]
